# Generated by Django 2.1.3 on 2018-12-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helphab_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionstable',
            old_name='date',
            new_name='date_time',
        ),
    ]
