# Generated by Django 2.1.3 on 2018-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphab_app', '0002_auto_20181210_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='address_one',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='address_two',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='city',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='state',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='facebook',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='gplus',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='twitter',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
