# Generated by Django 2.1.3 on 2018-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphab_app', '0003_auto_20181210_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='phone_number',
            new_name='address_one',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='gplus',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='twitter',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='address_two',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='state',
            field=models.CharField(default='null', max_length=2),
            preserve_default=False,
        ),
    ]
